# Generated by Django 3.1.5 on 2021-01-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('stats', models.JSONField(blank=True, null=True)),
                ('evolution', models.JSONField(blank=True, null=True)),
                ('prevolution', models.IntegerField(blank=True, null=True)),
                ('chain', models.IntegerField()),
            ],
        ),
    ]
