# Generated by Django 3.1.5 on 2021-01-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolutions',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolves_from',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolves_to',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
