# Generated by Django 3.1.5 on 2021-01-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20210116_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolves_to',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pokedex.pokemon'),
            preserve_default=False,
        ),
    ]
